#!/bin/sh
# check if we are on real system
if [ -z "$${IPKG_INSTROOT}" ]; then
        /etc/init.d/announce_services stop
        echo "Removing rc.d symlink for announce_services"
	/etc/init.d/announce_services disable
fi
exit 0
endef