#!/bin/sh /etc/rc.common

# This script should not have the same name as one of the binaries
# that gets launched by it, otherwise it terminates itself rather
# than shutting down cleanly.

START=94
STOP=1

start() {
	announce & # & is important, otherwise boot hangs
}

stop() {
	killall announce >/dev/null 2>&1
}
